# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Quartile Limited
org_slug: qrtl
rebel_module_groups: []
repo_description: null
repo_name: Custom modules
repo_slug: mi7-custom
repo_website: https://github.com/qrtl/mi7-custom
travis_apt_packages: []
travis_apt_sources: []
